"""Add sale status

Revision ID: 9ee93bab31ca
Revises: 6bd7f1466a29
Create Date: 2026-08-28 13:39:49.231919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee93bab31ca'
down_revision: Union[str, Sequence[str], None] = '6bd7f1466a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    # Add status with a temporary default so existing
    # sales receive a valid value instead of NULL.
    op.add_column(
        'sales',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=False,
            server_default='ACTIVE',
        ),
    )

    # Remove the temporary database default after the
    # existing rows have been populated.
    op.alter_column(
        'sales',
        'status',
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'status')
    # ### end Alembic commands ###
