from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field


# =========================================================
# INVENTORY CREATE SCHEMA
# =========================================================
# Used when creating an inventory record for a product.
#
# Example:
# POST /inventory/
#
# {
#     "product_id": 1,
#     "quantity": 50
# }
class InventoryCreate(BaseModel):

    # Product whose stock we want to manage.
    #
    # The database ForeignKey will make sure that this
    # product actually exists.
    product_id: int = Field(gt=0)

    # Initial stock quantity.
    #
    # ge=0 means quantity can be 0, but never negative.
    quantity: int = Field(
        default=0,
        ge=0,
    )


# =========================================================
# INVENTORY UPDATE SCHEMA
# =========================================================
# Used for a complete inventory update.
#
# PUT /inventory/{inventory_id}
#
# Since this is PUT, all fields are supplied by the client.
class InventoryUpdate(BaseModel):

    # Product associated with this inventory record.
    product_id: int = Field(gt=0)

    # Current stock quantity.
    # Negative inventory is not allowed.
    quantity: int = Field(
        ge=0,
    )


# =========================================================
# INVENTORY RESPONSE SCHEMA
# =========================================================
# Used when sending inventory information back to the client.
#
# The client does not send this schema.
# FastAPI uses it to control the response structure.
class InventoryResponse(BaseModel):

    # Allows Pydantic to read values directly from
    # the SQLAlchemy Inventory model.
    model_config = ConfigDict(from_attributes=True)

    id: int

    product_id: int

    quantity: int

    # These timestamps are generated by the database.
    created_at: datetime
    updated_at: datetime

# =========================================================
# STOCK MOVEMENT SCHEMA
# =========================================================
# Used for stock-in and stock-out operations.
#
# Example:
# {
#     "quantity": 20
# }
#
# The quantity represents how many units are being moved.
# It must always be greater than zero.
class StockMovement(BaseModel):

    # Number of units being added or removed.
    #
    # gt=0 means:
    # 1, 2, 3...  → valid
    # 0           → invalid
    # -5          → invalid
    #
    # We use a positive number here because the API endpoint
    # itself decides whether the operation is + (stock in)
    # or - (stock out).
    quantity: int = Field(
        gt=0,
    )