
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------
# Product Create Schema
# ---------------------------------------------------------
# Used when creating a new product through POST /products/
#
# These are the fields that the client is allowed/required
# to send while creating a product.
# The database-generated fields like id and is_active are
# not required from the client.

class ProductCreate(BaseModel):

    # Product name must contain at least 1 character
    # and cannot exceed 150 characters.
    name: str = Field(
        min_length=1,
        max_length=150,
    )

    # Decimal is used for money instead of float
    # to avoid floating-point precision problems.
    price: Decimal = Field(gt=0)

    # ID of the category to which this product belongs.
    # The database foreign key ensures that the category exists.
    category_id: int = Field(gt=0)


# ---------------------------------------------------------
# Product Update Schema
# ---------------------------------------------------------
# Used by PUT /products/{product_id}
#
# PUT represents a complete update, so all product fields
# are required in the request.

class ProductUpdate(BaseModel):

    name: str = Field(
        min_length=1,
        max_length=150,
    )

    price: Decimal = Field(gt=0)

    category_id: int = Field(gt=0)

    is_active: bool


# ---------------------------------------------------------
# Product Patch Schema
# ---------------------------------------------------------
# Used by PATCH /products/{product_id}
#
# PATCH allows partial updates.
# Therefore, every field is optional.
#
# Example:
# {
#     "price": 90000
# }
#
# In this case, only the price will be changed.

class ProductPatch(BaseModel):

    name: str | None = Field(
        default=None,
        min_length=1,
        max_length=150,
    )

    price: Decimal | None = Field(
        default=None,
        gt=0,
    )

    category_id: int | None = Field(
        default=None,
        gt=0,
    )

    is_active: bool | None = None


# ---------------------------------------------------------
# Product Response Schema
# ---------------------------------------------------------
# Used when sending product information back to the client.
#
# The client does not send this schema.
# FastAPI uses it to control/format the API response.

class ProductResponse(BaseModel):

    # Allows Pydantic to read data directly from
    # SQLAlchemy model objects.
    model_config = ConfigDict(from_attributes=True)

    # Generated by PostgreSQL.
    id: int

    name: str

    price: Decimal

    # Foreign key pointing to categories.id
    category_id: int

    # False means the product has been soft-deleted.
    is_active: bool