from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, Field

from app.schemas.sale_item import (
    SaleItemCreate,
    SaleItemResponse,
    
)


# =========================================================
# SALE CREATE SCHEMA
# =========================================================
# Used when creating a new sale.
#
# Example:
#
# {
#     "customer_id": 1,
#     "user_id": 1,
#     "items": [
#         {
#             "product_id": 3,
#             "quantity": 2
#         }
#     ]
# }
class SaleCreate(BaseModel):

    # Customer who is purchasing the products.
    customer_id: int

    # User/staff member who created the sale.
    user_id: int

    # Products included in this sale.
    #
    # At least one item must be present.
    items: list[SaleItemCreate] = Field(
        min_length=1,
    )

# =========================================================
# SALES SUMMARY RESPONSE
# =========================================================
# Used by:
#
# GET /sales/summary
#
# Provides aggregated sales statistics.
class SaleSummaryResponse(BaseModel):

    # Total number of sales, including cancelled sales.
    total_sales: int

    # Number of currently active sales.
    active_sales: int

    # Number of cancelled sales.
    cancelled_sales: int

    # Revenue generated by active sales only.
    total_revenue: Decimal

# =========================================================
# SALES REVENUE RESPONSE
# =========================================================
# Used by:
#
# GET /sales/revenue
#
# Provides revenue for a selected date/time range.
class SaleRevenueResponse(BaseModel):

    # Beginning of the requested date range.
    from_date: datetime

    # End of the requested date range.
    to_date: datetime

    # Number of active sales in the range.
    total_sales: int

    # Revenue generated by active sales.
    total_revenue: Decimal

# =========================================================
# SALE RESPONSE SCHEMA
# =========================================================
# Returned after creating or retrieving a sale.
class SaleResponse(BaseModel):

    id: int

    customer_id: int

    user_id: int

    sale_date: datetime

    total_amount: Decimal

    # Current state of the sale.
    status: str

    created_at: datetime

    updated_at: datetime

    # Sale items belonging to this sale.
    items: list[SaleItemResponse] = []
